# Generated by Django 3.0.14 on 2022-04-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_name',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
    ]
