# Generated by Django 3.0.14 on 2022-04-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_books_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='published_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
