# Generated by Django 3.0.14 on 2022-04-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_books_published_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Comic', 'Comic'), ('Historical', 'Historical'), ('Classics', 'Classics')], default=False, max_length=100),
        ),
    ]
