# Generated by Django 3.0.14 on 2022-04-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_books_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
    ]
