# Generated by Django 3.0.14 on 2022-04-05 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20220405_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='published_on',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
