# Generated by Django 3.0.14 on 2022-04-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20220405_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='published_on',
            field=models.DateField(null=True),
        ),
    ]
