# Generated by Django 3.0.14 on 2022-04-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20220406_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='published_on',
        ),
    ]
